package com.ecommerce.gocgac.entity.enums;

public enum ProductType {
    PHYSICAL,      // Sản phẩm vật lý: quần áo, thiết bị, đồ dùng...
    DIGITAL,       // Sản phẩm số: khóa học online, ebook, phần mềm...
    SERVICE,       // Dịch vụ: tư vấn, bảo hành, vận chuyển...
    VOUCHER        // Voucher, coupon
}
